#!/bin/sh

# symlink yadm archive
ln -sf ~/.config/dotfiles-secrets/hosts/gentoo-personal-laptop/yadm_archive ~/.local/share/yadm/archive
# decrypt secrets
yadm decrypt

# import gpg signing keys
gpg --import ~/.gpg/gentoo-personal-laptop-github.gpg

# set yadm origin as ssh
yadm remote set-url origin git@github.com:PedroJoaoPereira/dotfiles-gentoo-personal-laptop.git

# symlink portage configurations
doas ln -sf ~/.config/portage/* /etc/portage/

